### ISSUE TITLE
Function/Functions is not the right word of choice.

### ISSUE THREAD

**Issue by tagrudev** [uohzxela/clean-code-ruby#15]
I've seen that you have used `Functions` as a term in several places, that's not really correct.

> In Ruby it isn't possible to execute a piece of code that isn't defined on an object, because there is nothing in Ruby that is not an object - this way, strictly speaking, a concept of a function does not exist, there are only methods.

**Comment by uohzxela** [comment]
Great observation, will correct it in due course.

**Comment by uohzxela** [comment]
Adding `help wanted` label because of my limited bandwidth to work on this issue at the moment.
