### ISSUE TITLE
Function arguments example should have 2 arguments

### ISSUE THREAD

**Issue by david-pm** [uohzxela/clean-code-ruby#24]
The function [arguments section](https://github.com/uohzxela/clean-code-ruby#function-arguments-2-or-fewer-ideally) talks about rarely using over two arguments in a single method. We should probably give an example that doesn't use four arguments.

 **Bad:**
 ```ruby
-def create_menu(title, body, button_text, cancellable)
+def create_menu(title, body)
   # ...
 end
 ```

 **Good:**
 ```ruby
-def create_menu(title:, body:, button_text:, cancellable:)
+def create_menu(title:, body:)
   # ...
 end

-create_menu(
-  title: 'Foo',
-  body: 'Bar',
-  button_text: 'Baz',
-  cancellable: true
-)
+create_menu(title: 'Foo', body: 'Bar')
 ```

Would be happy to push up a PR for the above :)

**Comment by uohzxela** [comment]
Good catch! Please feel free to submit a PR for this.

**Comment by david-pm** [comment]
https://github.com/uohzxela/clean-code-ruby/pull/27
