### ISSUE TITLE
Add a description to "Function names should say what they do"

### ISSUE THREAD

**Issue by david-pm** [uohzxela/clean-code-ruby#25]
I noticed there was no description under [Function names should say what they do](https://github.com/uohzxela/clean-code-ruby#function-names-should-say-what-they-do). I'd like to suggest something like the following:

```
### Function names should say what they do

Poorly named methods add to the code reviewer's cognitive load at best, and mislead the
code reviewer at worst. Strive to capture the the precise intent when naming methods.
```

**Comment by uohzxela** [comment]
Sounds good! Please feel free to submit a PR for this.
