### ISSUE TITLE
using attr_accessor is a code smell, read more here. (redirect to porno site)

### ISSUE THREAD

**Issue by valterfernandesdev** [uohzxela/clean-code-ruby#40]
"However, you have to be aware that in some situations, using attr_accessor is a code smell, read more here." Check this link, ASAP!

**Comment by zokioki** [comment]
Seems like this is the link that was meant to be referenced (note the `.codes` vs `.eu`):
https://solnic.codes/2012/04/04/get-rid-of-that-code-smell-attributes/

**Comment by valterfernandesdev** [comment]
Yes, but somehow is not hitting the correct url!

**Comment by valterfernandesdev** [comment]
Actually the link is: 

> http://solnic.eu/2012/04/04/get-rid-of-that-code-smell-attributes.html

Inpect the element and you'll see.

**Comment by zokioki** [comment]
Yes, what I meant is the link should be changed in the repo to the one I posted - submitted a PR! ☝️

**Comment by uohzxela** [comment]
Thanks all for the catch. I guess the DNS mapping has changed since the last time I accessed the link. Closing this issue since the PR has been merged.
